# Generated by Django 3.2.5 on 2022-10-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование сырья')),
                ('count_iron', models.FloatField(verbose_name='Содержание железа')),
                ('count_silicon', models.FloatField(verbose_name='Содержание кремния')),
                ('count_aluminum', models.FloatField(verbose_name='Содержание алюминия')),
                ('count_calcium', models.FloatField(verbose_name='Содержание кальция')),
                ('count_sulfur', models.FloatField(verbose_name='Содержание серы')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesapp.date')),
            ],
        ),
    ]
