# Generated by Django 3.2.5 on 2022-10-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTable',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
