# Generated by Django 3.2.5 on 2022-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablesapp', '0002_auto_20221023_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование сырья')),
                ('count_iron', models.FloatField(verbose_name='Содержание железа')),
                ('count_silicon', models.FloatField(verbose_name='Содержание кремния')),
                ('count_aluminum', models.FloatField(verbose_name='Содержание алюминия')),
                ('count_calcium', models.FloatField(verbose_name='Содержание кальция')),
                ('count_sulfur', models.FloatField(verbose_name='Содержание серы')),
                ('date', models.DateField()),
            ],
        ),
    ]
